# Generated by Django 4.2.17 on 2025-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='travelpackage',
            options={'verbose_name': 'Pacote De Viagem', 'verbose_name_plural': 'Pacotes De Viagens'},
        ),
        migrations.AddField(
            model_name='travelpackage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
